name: Android Build

on:
  push:
    branches:
      - android-build-github
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend/android-native

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Decrypt google-services.json
      run: |
        echo "${{ secrets.FIREBASE_CONFIG }}" | base64 -d > app/google-services.json

    - name: Decrypt local.properties
      run: |
        echo "${{ secrets.LOCAL_PROPERTIES }}" | base64 -d > local.properties

    - name: Build with Gradle
      run: ./gradlew build 
